---
permalink: online-help/concept-what-happens-when-a-performance-threshold-policy-is-changed-opm.html 
sidebar: sidebar 
keywords:  
summary: Se você ajustar o valor do contador ou a duração de uma política de limite de desempenho existente, a alteração de política será aplicada a todos os objetos de armazenamento que usam a diretiva. A nova configuração ocorre imediatamente e o Unified Manager começa a comparar os valores do contador de desempenho com as novas configurações de limite para todos os dados de desempenho recém-coletados. 
---
= O que acontece quando uma política de limite de desempenho é alterada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você ajustar o valor do contador ou a duração de uma política de limite de desempenho existente, a alteração de política será aplicada a todos os objetos de armazenamento que usam a diretiva. A nova configuração ocorre imediatamente e o Unified Manager começa a comparar os valores do contador de desempenho com as novas configurações de limite para todos os dados de desempenho recém-coletados.

Se existirem eventos ativos para objetos que estejam usando a política de limite alterada, os eventos serão marcados como obsoletos e a política de limite começará a monitorar o contador como uma política de limite recém-definida.

Ao visualizar o contador no qual o limite foi aplicado na Exibição detalhada dos gráficos de Contador, as linhas de limite crítico e de aviso refletem as configurações de limite atuais. As configurações de limite originais não aparecem nesta página, mesmo que você exiba dados históricos quando a configuração de limite antiga estava em vigor.

[NOTE]
====
Como as configurações de limite mais antigas não aparecem na Exibição detalhada dos gráficos de Contador, você pode ver eventos históricos que aparecem abaixo das linhas de limite atuais.

====