---
permalink: online-help/concept-overview-of-the-quota-process-um-6-1.html 
sidebar: sidebar 
keywords:  
summary: As quotas podem ser suaves ou difíceis. As cotas flexíveis fazem com que o ONTAP envie uma notificação quando os limites especificados forem excedidos e as cotas rígidas impedem que uma operação de gravação seja bem-sucedida quando os limites especificados forem excedidos. 
---
= Visão geral do processo de cota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As quotas podem ser suaves ou difíceis. As cotas flexíveis fazem com que o ONTAP envie uma notificação quando os limites especificados forem excedidos e as cotas rígidas impedem que uma operação de gravação seja bem-sucedida quando os limites especificados forem excedidos.

Quando o ONTAP recebe uma solicitação de um usuário ou grupo de usuários para gravar em um FlexVol volume, ele verifica se as cotas estão ativadas nesse volume para o usuário ou grupo de usuários e determina o seguinte:

* Se o limite rígido será atingido
+
Se sim, a operação de gravação falha quando o limite rígido é atingido e a notificação de cota rígida é enviada.

* Se o limite flexível será violado
+
Se sim, a operação de gravação é bem-sucedida quando o limite de software é violado e a notificação de cota de software é enviada.

* Se uma operação de gravação não excederá o limite de software
+
Se sim, a operação de gravação é bem-sucedida e nenhuma notificação é enviada.


