---
permalink: online-help/concept-volume-performance-explorer-page.html 
sidebar: sidebar 
keywords:  
summary: Esta página fornece informações detalhadas sobre o desempenho de um volume em um cluster. O título desta página depende se você está visualizando um volume FlexVol volume ou FlexGroup. 
---
= Página desempenho/volume ou desempenho/Explorador do FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta página fornece informações detalhadas sobre o desempenho de um volume em um cluster. O título desta página depende se você está visualizando um volume FlexVol volume ou FlexGroup.

A página Explorador de volume ou FlexGroup permite-lhe monitorizar e comparar o desempenho do volume durante um período de tempo específico, o que o ajuda a resolver problemas e a ajustar o desempenho do volume.

[NOTE]
====
Os volumes raiz não são exibidos nesta página.

====
Utilizar a funcionalidade Ver e comparar:

* Para o FlexVol volumes, você pode comparar a performance desse volume com:
+
** outros volumes no mesmo agregado
** o agregado no qual esse volume reside
** O SVM no qual esse volume reside
** Os LUNs que estão neste volume


* Para o FlexGroup volumes, você pode comparar o desempenho deste FlexGroup com:
+
** Os agregados em que o FlexGroup reside
** O SVM no qual o FlexGroup reside
** Os volumes constituintes do FlexGroup




As estatísticas nos gráficos são atualizadas após cada período de coleta; que por padrão é a cada 5 minutos. O seletor Exibir estatísticas no fornece uma opção para mostrar as estatísticas médias na hora anterior. Essa funcionalidade permite que você visualize o gráfico de latência em suporte ao programa "Garantia de desempenho" da NetApp.

A página Explorador de desempenho/volume ou Explorador de desempenho/FlexGroup permite-lhe:

* Veja os problemas relacionados ao limite e seus detalhes
* Acompanhe e compare os dados de desempenho do volume
* Investigue e solucione problemas relacionados ao limite
* Investigue e solucione problemas de desempenho
* Inicie o System Manager para alterar a configuração do volume
+
O botão *Configurar volume* está disponível se você estiver conetado ao Gerenciador Unificado com a função Administrador do OnCommand ou Administrador do armazenamento e ao usar o ONTAP 9.5 ou superior.



[NOTE]
====
Para volumes de proteção de dados (DP), somente os valores de contador para tráfego gerado pelo usuário são exibidos. Quando o cluster é instalado com uma versão do software ONTAP anterior a 8,3, não são apresentados valores de contador.

====