---
permalink: online-help/reference-volume-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: A página limites de configuração/integridade para volumes permite configurar valores de limite de integridade global para volumes monitorados. Você pode definir limites para volumes individuais ou para todos os volumes globalmente. Quando você configura as opções globalmente, os valores padrão de todos os objetos são modificados. No entanto, se os valores padrão tiverem sido alterados no nível do objeto, os valores globais não serão modificados. 
---
= Página de limites de configuração/integridade para volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A página limites de configuração/integridade para volumes permite configurar valores de limite de integridade global para volumes monitorados. Você pode definir limites para volumes individuais ou para todos os volumes globalmente. Quando você configura as opções globalmente, os valores padrão de todos os objetos são modificados. No entanto, se os valores padrão tiverem sido alterados no nível do objeto, os valores globais não serão modificados.

Você deve ter a função Administrador do OnCommand ou Administrador do armazenamento.

Os eventos são gerados quando um limite é violado. Você pode tomar ações corretivas para tais eventos.

Você pode definir limites para: Capacidade, cópias Snapshot de volume, cotas, crescimento de volume e inodes.



== Área de capacidade

A área capacidade permite definir as seguintes condições de limite de capacidade de volume. Observe que, quando o crescimento automático está ativado em um volume, os limites de capacidade são considerados violados com base no tamanho máximo do volume definido pelo crescimento automático, não com base no tamanho do volume original.

* *Espaço quase cheio*
+
Especifica a porcentagem em que um volume é considerado quase cheio:

+
** Valor padrão: 80 por cento
+
O valor para esse limite deve ser menor do que o valor do limite volume cheio para que o servidor de gerenciamento gere um evento.

** Evento gerado: Volume quase cheio
** Gravidade do evento: Aviso


* *Espaço cheio*
+
Especifica a porcentagem em que um volume é considerado cheio:

+
** Valor padrão: 90 por cento
** Evento gerado: Volume cheio
** Gravidade do evento: Erro


* *Dias até completo*
+
Especifica o número de dias restantes antes de o volume atingir a capacidade total:

+
** Valor padrão: 7
** Evento gerado: Dias volume até cheio
** Gravidade do evento: Erro






== Área cópias Snapshot

A área cópias Snapshot permite definir as seguintes condições de limite para as cópias Snapshot no volume:

* *Reserva Snapshot completa*
+
Especifica a porcentagem em que o espaço reservado para cópias Snapshot é considerado cheio:

+
** Valor padrão: 90 por cento
** Evento gerado: Reserva Snapshot volume cheia
** Gravidade do evento: Erro


* *Dias até completo*
+
Especifica o número de dias restantes antes que o espaço reservado para cópias Snapshot alcance a capacidade total:

+
** Valor padrão: 7
** Evento gerado: Dias reserva Snapshot volume até cheio
** Gravidade do evento: Erro


* *Contagem*
+
Especifica o número de cópias snapshot em um volume que é considerado muito:

+
** Valor padrão: 250
** Evento gerado: Muitas cópias Snapshot
** Gravidade do evento: Erro






== Área de cota Qtree

A área de cota Qtree permite definir as seguintes condições de limite de cota de volume:

* * Quase exagerado*
+
Especifica a porcentagem em que um volume é considerado quase sobrecarregado por cotas de qtree:

+
** Valor padrão: 95 por cento
** Evento gerado: Volume Qtree quota quase comprometida
** Gravidade do evento: Aviso


* * Overcommitted*
+
Especifica a porcentagem em que um volume é considerado sobrecarregado por cotas de qtree:

+
** Valor padrão: 100 por cento
** Evento gerado: Cota de volume Qtree sobrecomprometida
** Gravidade do evento: Erro






== Área de crescimento

A área de crescimento permite definir as seguintes condições de limite para o crescimento de volume:

* *Taxa de crescimento*
+
Especifica a percentagem em que a taxa de crescimento de um volume é considerada normal antes de o sistema gerar um evento anormal da taxa de crescimento de volume:

+
** Valor padrão: 1 por cento
** Evento gerado: Taxa de crescimento do volume anormal
** Gravidade do evento: Aviso


* * Sensibilidade da taxa de crescimento*
+
Especifica o fator que é aplicado ao desvio padrão da taxa de crescimento de um volume. Se a taxa de crescimento exceder o desvio padrão fatorado, é gerado um evento anormal da taxa de crescimento do volume.

+
Um valor mais baixo para a sensibilidade da taxa de crescimento indica que o volume é altamente sensível às mudanças na taxa de crescimento. O intervalo para a sensibilidade da taxa de crescimento é de 1 a 5.

+
** Valor padrão: 2


+
[NOTE]
====
Se você modificar a sensibilidade da taxa de crescimento para volumes no nível do limiar global, a mudança também será aplicada à sensibilidade da taxa de crescimento para agregados no nível do limiar global.

====




== Área de inodes

A área inodes permite definir as seguintes condições de limite para inodes:

* *Quase cheio*
+
Especifica a porcentagem em que um volume é considerado como tendo consumido a maioria de seus inodes:

+
** Valor padrão: 80 por cento
** Evento gerado: Inodes quase cheio
** Gravidade do evento: Aviso


* *Full*
+
Especifica a porcentagem na qual um volume é considerado ter consumido todos os seus inodes:

+
** Valor padrão: 90 por cento
** Evento gerado: Inodes Full
** Gravidade do evento: Erro






== Botões de comando

* *Restaurar para padrões de fábrica*
+
Permite restaurar as definições de configuração para os valores predefinidos de fábrica.

* *Guardar*
+
Guarda as definições de configuração para a opção selecionada.


