---
permalink: online-help/reference-add-alert-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Você pode criar alertas para notificá-lo quando um evento específico é gerado, para que você possa resolver o problema rapidamente e, assim, minimizar o impactos no seu ambiente. Você pode criar alertas para um único recurso ou um conjunto de recursos e para eventos de um tipo de gravidade específico. Você também pode especificar o método de notificação e a frequência dos alertas. 
---
= Caixa de diálogo Adicionar alerta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar alertas para notificá-lo quando um evento específico é gerado, para que você possa resolver o problema rapidamente e, assim, minimizar o impactos no seu ambiente. Você pode criar alertas para um único recurso ou um conjunto de recursos e para eventos de um tipo de gravidade específico. Você também pode especificar o método de notificação e a frequência dos alertas.

Você deve ter a função Administrador do OnCommand ou Administrador do armazenamento.



== Nome

Esta área permite especificar um nome e uma descrição para o alerta:

* *Nome do alerta*
+
Permite especificar um nome de alerta.

* *Descrição do alerta*
+
Permite especificar uma descrição para o alerta.





== Recursos

Essa área permite selecionar um recurso individual ou agrupar os recursos com base em uma regra dinâmica para a qual você deseja acionar o alerta. Uma regra _dinâmica_ é o conjunto de recursos filtrados com base na cadeia de texto especificada. Você pode pesquisar recursos selecionando um tipo de recurso na lista suspensa ou especificar o nome exato do recurso para exibir um recurso específico.

Se você estiver criando um alerta a partir de qualquer uma das páginas de detalhes do objeto de armazenamento, o objeto de armazenamento será incluído automaticamente no alerta.

* *Incluir*
+
Permite incluir os recursos para os quais você deseja acionar alertas. Você pode especificar uma cadeia de texto para agrupar recursos que correspondem à cadeia de carateres e selecionar esse grupo a ser incluído no alerta. Por exemplo, você pode agrupar todos os volumes cujo nome contém a string "'abc'".

* *Excluir*
+
Permite excluir recursos para os quais você não deseja acionar alertas. Por exemplo, você pode excluir todos os volumes cujo nome contém a string "'xyz".

+
A guia Excluir é exibida somente quando você seleciona todos os recursos de um tipo de recurso específico: Por exemplo, <<All Volumes>> ou <<All Volumes whose name contains '_xyz_'>>.

+
Se um recurso estiver em conformidade com as regras incluir e excluir que você especificou, a regra excluir terá precedência sobre a regra incluir e o alerta não será gerado para o evento.





== Eventos

Esta área permite-lhe selecionar os eventos para os quais pretende criar os alertas. Você pode criar alertas para eventos com base em uma gravidade específica ou em um conjunto de eventos.

Para selecionar mais de um evento, mantenha pressionada a tecla Ctrl enquanto faz as seleções.

* *Gravidade do evento*
+
Permite selecionar eventos com base no tipo de gravidade, que pode ser crítico, erro ou Aviso.

* *Nome do evento contém*
+
Permite selecionar eventos cujo nome contém carateres especificados.





== Ações

Essa área permite especificar os usuários que você deseja notificar quando um alerta é acionado. Você também pode especificar o método de notificação e a frequência da notificação.

* *Alertar esses usuários*
+
Permite especificar o endereço de e-mail ou o nome de usuário do usuário para receber notificações.

+
Se você modificar o endereço de e-mail especificado para o usuário e reabrir o alerta para edição, o campo Nome será exibido em branco porque o endereço de e-mail modificado não será mais mapeado para o usuário selecionado anteriormente. Além disso, se você tiver modificado o endereço de e-mail do usuário selecionado na página Gerenciamento/usuários, o endereço de e-mail modificado não será atualizado para o usuário selecionado.

* *Frequência de notificação*
+
Permite especificar a frequência com que o servidor de gerenciamento envia notificações até que o evento seja reconhecido, resolvido ou movido para o estado obsoleto.

+
Você pode escolher os seguintes métodos de notificação:

+
** Notificar apenas uma vez
** Notificar a uma frequência especificada
** Notificar a uma frequência especificada dentro do intervalo de tempo especificado


* *Emitir trap SNMP*
+
Selecionar esta caixa permite especificar se as traps SNMP devem ser enviadas para o host SNMP configurado globalmente.

* *Execute Script*
+
Permite-lhe adicionar o seu script personalizado ao alerta. Este script é executado quando um alerta é gerado.





== Botões de comando

* *Guardar*
+
Cria um alerta e fecha a caixa de diálogo.

* *Cancelar*
+
Descarta as alterações e fecha a caixa de diálogo.


