---
permalink: online-help/task-viewing-the-volume-list-and-details.html 
sidebar: sidebar 
keywords:  
summary: Na página de inventário de integridade/volumes, você pode monitorar seu inventário de volumes. A página integridade/capacidade de volumes e utilização permite visualizar informações sobre a capacidade e a utilização de volumes em um cluster. 
---
= Visualizar a lista de volumes e os detalhes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na página de inventário de integridade/volumes, você pode monitorar seu inventário de volumes. A página integridade/capacidade de volumes e utilização permite visualizar informações sobre a capacidade e a utilização de volumes em um cluster.



== Antes de começar

Você deve ter a função Operador, Administrador OnCommand ou Administrador de armazenamento.



== Sobre esta tarefa

Você também pode usar a página Detalhes de integridade/volume para exibir informações detalhadas sobre volumes monitorados, incluindo a capacidade, eficiência, configuração e proteção dos volumes. Você também pode exibir informações sobre os dispositivos relacionados e alertas relacionados para um volume específico.



== Passos

. No painel de navegação à esquerda, clique em *Health* > *volumes*.
. Escolha uma das seguintes formas de visualizar os detalhes do volume:
+
** Para exibir informações detalhadas sobre a capacidade e utilização de volumes em um cluster, no menu Exibir, selecione *capacidade de volume e utilização*.
** Para ver detalhes mínimos, posicione o cursor sobre o nome do volume.
** Para ver os detalhes completos, clique no nome do volume.
+
Você também pode visualizar os detalhes completos clicando em *Exibir detalhes* na caixa de diálogo Detalhes mínimos.



. Visualize os objetos relacionados ao volume clicando em *Exibir relacionado* na caixa de diálogo Detalhes mínimos.

