---
permalink: online-help/task-resynchronizing-protection-relationships.html 
sidebar: sidebar 
keywords:  
summary: Na página relacionamentos de proteção/volume, você pode ressincronizar um relacionamento para recuperar de um evento que desabilitou o volume de origem ou quando deseja alterar a fonte atual para um volume diferente. 
---
= Ressincronizar relações de proteção a partir da página relacionamentos de proteção/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na página relacionamentos de proteção/volume, você pode ressincronizar um relacionamento para recuperar de um evento que desabilitou o volume de origem ou quando deseja alterar a fonte atual para um volume diferente.



== Antes de começar

* Você deve ter a função Administrador do OnCommand ou Administrador do armazenamento.
* Você deve ter configurado o Workflow Automation.




== Passos

. Na página *relacionamentos de proteção/volume*, selecione um ou mais volumes com relacionamentos quiesced e, na barra de ferramentas, clique em *Resynchronize*.
+
A caixa de diálogo Resyncronizar é exibida.

. Na guia *Opções de ressincronização*, selecione uma prioridade de transferência e a taxa de transferência máxima.
. Clique em *cópias snapshot de origem*; em seguida, na coluna *cópia Snapshot*, clique em *predefinição*.
+
A caixa de diálogo Selecionar cópia Snapshot de origem é exibida.

. Se você quiser especificar uma cópia Snapshot existente em vez de transferir a cópia Snapshot padrão, clique em *cópia Snapshot existente* e selecione uma cópia Snapshot na lista.
. Clique em *Enviar*.
+
Você será retornado à caixa de diálogo Resyncronizar.

. Se você selecionou mais de uma fonte para ressincronizar, clique em *Default* para a próxima fonte para a qual deseja especificar uma cópia Snapshot existente.
. Clique em *Enviar* para iniciar o trabalho de ressincronização.
+
O trabalho de ressincronização é iniciado, você retorna à página Relações de proteção/volume e um link trabalhos é exibido na parte superior da página.

. Clique em *Exibir tarefas* na página *relacionamentos de proteção/volume* para rastrear o status de cada trabalho de ressincronização.
+
É apresentada uma lista filtrada de trabalhos.

. Clique na seta *voltar* no navegador para retornar à página *relacionamentos de proteção/volume*.
+
A operação de ressincronização é concluída quando todas as tarefas de trabalho forem concluídas com êxito.


