---
permalink: online-help/task-editing-storage-class-threshold-settings.html 
sidebar: sidebar 
keywords:  
summary: Quando você precisa resolver quaisquer problemas relacionados ao espaço de armazenamento em suas classes de armazenamento, você pode editar as configurações de limite da capacidade da classe de armazenamento com base nos requisitos da sua organização. Quando o limite é cruzado, os eventos são gerados e você recebe notificações se tiver configurado alertas para tais eventos. 
---
= Editar as definições de limite das classes de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você precisa resolver quaisquer problemas relacionados ao espaço de armazenamento em suas classes de armazenamento, você pode editar as configurações de limite da capacidade da classe de armazenamento com base nos requisitos da sua organização. Quando o limite é cruzado, os eventos são gerados e você recebe notificações se tiver configurado alertas para tais eventos.



== Antes de começar

Você deve ter a função Administrador do OnCommand ou Administrador do armazenamento.



== Passos

. No painel de navegação esquerdo, clique em *Health* > *SVMs*.
. Na página de inventário *máquinas virtuais de integridade/storage*, selecione um SVM com Infinite volume.
. Na página de detalhes *Health/Storage Virtual Machine*, clique em *Actions* > *Edit thresholds* (ações* > Editar limites*).
. Na caixa de diálogo *Editar limites de classe de armazenamento*, modifique os limites conforme necessário.
. Clique em *Salvar e fechar*.

