---
permalink: online-help/task-editing-clusters.html 
sidebar: sidebar 
keywords:  
summary: Você pode modificar as configurações de um cluster existente, como o nome do host ou endereço IP, nome de usuário, senha, protocolo e porta, usando a caixa de diálogo Editar cluster. 
---
= Edição de clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode modificar as configurações de um cluster existente, como o nome do host ou endereço IP, nome de usuário, senha, protocolo e porta, usando a caixa de diálogo Editar cluster.



== Antes de começar

Você deve ter a função Administrador do OnCommand ou a função Administrador do armazenamento.



== Sobre esta tarefa

[NOTE]
====
Se você alterar o endereço IP de um cluster para um endereço IP de um cluster monitorado existente, todos os dados do cluster existente serão perdidos quando o cluster anterior for descoberto. Não é apresentada uma mensagem de erro para o avisar.

====


== Passos

. No painel de navegação à esquerda, clique em *Configuração* > *fontes de dados do Cluster*.
. Na página *fontes de dados de Configuração/Cluster*, selecione o cluster que deseja editar e clique em *Editar*.
. Na caixa de diálogo *Editar Cluster*, modifique os valores conforme necessário.
. Clique em *Enviar*.

