---
permalink: online-help/task-restoring-a-mysql-database-backup-on-red-hat-enterprise-linux-or-centos.html 
sidebar: sidebar 
keywords: Unified Manager 
summary: Se ocorrer perda de dados ou corrupção de dados, você poderá restaurar o Unified Manager para o estado estável anterior com perda mínima de dados. É possível restaurar o banco de dados do Unified Manager para um sistema Red Hat Enterprise Linux ou CentOS local ou remoto. 
---
= Restaurar um backup de banco de dados em um sistema Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se ocorrer perda de dados ou corrupção de dados, você poderá restaurar o Unified Manager para o estado estável anterior com perda mínima de dados. É possível restaurar o banco de dados do Unified Manager para um sistema Red Hat Enterprise Linux ou CentOS local ou remoto.



== Antes de começar

* Você precisa ter o Unified Manager instalado em um servidor.
* Você deve ter as credenciais de usuário raiz para o host Linux no qual o Unified Manager está instalado.
* Você deve ter copiado o arquivo de backup do Unified Manager e o conteúdo do diretório do repositório do banco de dados para o sistema no qual você executará a operação de restauração.
+
É recomendável que você copie o arquivo de backup para o diretório padrão `/data/ocum-backup` . Os arquivos do repositório de banco de dados devem ser copiados para `/database-dumps-repo` o subdiretório sob o `/ocum-backup` diretório.

* Os ficheiros de cópia de segurança têm de ser `.7z` do tipo.




== Sobre esta tarefa

O recurso de restauração é específico da plataforma e específico da versão. Você pode restaurar um backup do Unified Manager somente na mesma versão do Unified Manager. É possível restaurar um arquivo de backup do Linux ou um arquivo de backup de dispositivo virtual para um sistema Red Hat Enterprise Linux ou CentOS.

[TIP]
====
Se o nome da pasta de backup contiver um espaço, você deve incluir o caminho absoluto ou caminho relativo em aspas duplas.

====


== Passos

. Se você estiver executando uma restauração em um novo servidor, após a instalação do Unified Manager, não inicie a IU nem configure clusters, usuários ou configurações de autenticação quando a instalação for concluída. O arquivo de backup preenche essas informações durante o processo de restauração.
. Faça login como usuário raiz no host no qual o Unified Manager está instalado.
. Se o Unified Manager estiver instalado na configuração VCS, pare os serviços de ocie e ocieau do Unified Manager usando o Veritas Operations Manager.
. No prompt de comando, restaure o backup: `um backup restore -f <backup_file_path>/<backup_file_name>`
+
`um backup restore -f /data/ocum-backup/UM_9.4.N151113.1348_backup_rhel_02-20-2018-04-45.7z`





== Depois de terminar

Após a conclusão da operação de restauração, você pode fazer login no Unified Manager.
