---
permalink: online-help/task-deleting-svm-associations.html 
sidebar: sidebar 
keywords:  
summary: Você pode excluir associações SVM para aplicações de parceiros para remover a relação de provisionamento secundário entre SVMs de origem e destino. Por exemplo, você pode fazer isso quando o SVM de destino estiver cheio e quiser criar uma nova associação de proteção SVM. 
---
= Exclusão de associações de SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode excluir associações SVM para aplicações de parceiros para remover a relação de provisionamento secundário entre SVMs de origem e destino. Por exemplo, você pode fazer isso quando o SVM de destino estiver cheio e quiser criar uma nova associação de proteção SVM.



== Antes de começar

Você deve ter a função Administrador do OnCommand ou Administrador do armazenamento.



== Sobre esta tarefa

O botão *Delete* é desativado até que pelo menos uma associação SVM seja selecionada. Alterar associações usando as funções excluir e criar afeta apenas operações futuras de provisionamento; ele não move volumes de destino existentes.



== Passos

. No painel de navegação à esquerda, clique em *proteção* > *associações SVM*.
. Selecione pelo menos uma associação SVM.
+
O botão *Delete* está ativado.

. Clique em *Excluir.*
+
É apresentada uma caixa de diálogo de aviso.

. Clique em *Yes* para continuar.
+
A associação SVM selecionada é removida da lista.


