---
permalink: online-help/task-removing-clusters.html 
sidebar: sidebar 
keywords:  
summary: Você pode remover um cluster do Unified Manager usando a página Configuration/Cluster Data Sources. Por exemplo, você pode remover um cluster se a descoberta de cluster falhar ou quando quiser desativar um sistema de storage. 
---
= Remoção de clusters
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover um cluster do Unified Manager usando a página Configuration/Cluster Data Sources. Por exemplo, você pode remover um cluster se a descoberta de cluster falhar ou quando quiser desativar um sistema de storage.



== Antes de começar

Você deve ter a função Administrador do OnCommand ou a função Administrador do armazenamento.



== Sobre esta tarefa

Esta tarefa remove o cluster selecionado do Unified Manager. Depois que um cluster é removido, ele não é mais monitorado. A instância do Unified Manager registrada com o cluster removido também não é registrada do cluster.

A remoção de um cluster também exclui todos os objetos de armazenamento, dados históricos, serviços de armazenamento e todos os eventos associados do Unified Manager. Essas alterações são refletidas nas páginas de inventário e nas páginas de detalhes após o próximo ciclo de coleta de dados.



== Passos

. No painel de navegação à esquerda, clique em *Configuração* > *fontes de dados do Cluster*.
. Na página *fontes de dados de Configuração/Cluster*, selecione o cluster que deseja remover e clique em *Remover*.
. Na caixa de diálogo *Remover fonte de dados*, clique em *Remover* para confirmar a solicitação de remoção.

