---
permalink: online-help/task-importing-reports.html 
sidebar: sidebar 
keywords:  
summary: Se você tiver criado um relatório fora do Unified Manager, poderá importar e salvar o arquivo de relatório a ser usado com o Unified Manager. 
---
= Importar relatórios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você tiver criado um relatório fora do Unified Manager, poderá importar e salvar o arquivo de relatório a ser usado com o Unified Manager.



== Antes de começar

Tem de ter a função de Administrador do OnCommand.

Você deve garantir que o relatório que pretende importar seja compatível com o Unified Manager.



== Passos

. No painel de navegação esquerdo, clique em *relatórios* e, em seguida, clique em *Importar relatório*.
. Na caixa de diálogo *Importar Relatório*, clique em *Procurar* e selecione o arquivo que deseja importar e, em seguida, insira um nome e uma breve descrição do relatório.
. Clique em *Importar*.
+
Se não conseguir importar o relatório, pode verificar o ficheiro de registo para encontrar o erro que está a causar o problema.


