---
permalink: online-help/task-calculating-reclaimable-space-for-snapshot-copies.html 
sidebar: sidebar 
keywords:  
summary: Você pode calcular a quantidade de espaço em disco que pode ser recuperado se uma ou mais cópias Snapshot forem excluídas. 
---
= Cálculo do espaço que pode ser recuperado para cópias Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode calcular a quantidade de espaço em disco que pode ser recuperado se uma ou mais cópias Snapshot forem excluídas.



== Antes de começar

Você deve ter a função Operador, Administrador OnCommand ou Administrador de armazenamento.

O volume deve estar online.



== Passos

. No painel de navegação à esquerda, clique em *Health* > *volumes*.
. Na página de inventário *Saúde/volumes*, selecione o volume que contém as cópias Snapshot que deseja exibir.
+
A lista de cópias Snapshot é exibida.

. Na página de detalhes *Saúde/volume*, clique na guia *capacidade*.
. No painel *Detalhes* da guia *capacidade*, na seção outros detalhes, clique no link ao lado de *cópias instantâneas*.
+
O número de cópias Snapshot é um link que exibe a lista de cópias snapshot.

. Na exibição *cópias Snapshot*, selecione as cópias Snapshot para as quais você deseja calcular o espaço que pode ser recuperado.
. Clique em *calcular*.
+
O espaço rereclamável (em porcentagem e KB, MB, GB e assim por diante) no volume é exibido.

. Para recalcular o espaço que pode ser recuperado, selecione as cópias Snapshot necessárias e clique em *Recalcular*.

