---
permalink: online-help/task-viewing-performance-threshold-policies.html 
sidebar: sidebar 
keywords:  
summary: Você pode exibir todas as políticas de limite de desempenho definidas atualmente na página limites de configuração/desempenho. 
---
= Exibindo políticas de limite de desempenho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir todas as políticas de limite de desempenho definidas atualmente na página limites de configuração/desempenho.



== Sobre esta tarefa

A lista de políticas de limite é ordenada alfabeticamente por nome de política e inclui políticas para todos os tipos de objetos de storage. Você pode clicar em um cabeçalho de coluna para classificar as políticas por essa coluna. Se você estiver procurando uma política específica, use os mecanismos de filtro e pesquisa para refinar a lista de políticas de limite que aparecem na lista de inventário.

Você pode passar o cursor sobre o Nome da política e o nome da condição para ver os detalhes de configuração da política. Além disso, você pode usar os botões fornecidos para criar, clonar, editar e excluir políticas de limite definidas pelo usuário.



== Passos

. No painel de navegação esquerdo, selecione *Configuração* > *limites de desempenho*.
+
É apresentada a página Configuration/Performance Thresholds (limites de configuração/desempenho).


