---
permalink: online-help/task-managing-report-schedules.html 
sidebar: sidebar 
keywords:  
summary: Você pode gerenciar suas agendas de relatórios na caixa de diálogo Gerenciar agendas de relatórios. Você pode adicionar uma nova programação e exibir, modificar ou excluir programações existentes. 
---
= Gerenciamento de programações de relatórios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar suas agendas de relatórios na caixa de diálogo Gerenciar agendas de relatórios. Você pode adicionar uma nova programação e exibir, modificar ou excluir programações existentes.



== Passos

. No painel de navegação à esquerda, clique em *relatórios* e, em seguida, clique em *Gerenciar agendas de relatórios*.
. Na caixa de diálogo *Gerenciar agendas de relatórios*,
+
|===
| Se você quiser... | Então... 


 a| 
Exibir ou modificar um agendamento existente
 a| 
.. Selecione a programação na lista exibida no painel esquerdo.
+
Os detalhes da programação são exibidos.

.. Faça as alterações necessárias.
.. Clique em *Salvar* ou *Salvar e fechar*.




 a| 
Eliminar uma agenda existente
 a| 
.. Selecione a programação na lista exibida no painel esquerdo.
+
Os detalhes da programação são exibidos.

.. Clique em *Excluir horário*.




 a| 
Adicione uma nova agenda
 a| 
.. Clique em *Add Schedule*.
.. Um novo formulário de agendamento aparece no painel direito.
.. Insira o nome da programação, o endereço de e-mail do destinatário, o formato e a frequência do relatório e selecione os relatórios que deseja agendar.
.. Clique em *Salvar*. O novo agendamento será adicionado na lista de horários.


|===

