---
permalink: online-help/task-initializing-or-updating-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: Você pode executar uma transferência de linha de base pela primeira vez em um novo relacionamento de proteção ou atualizar um relacionamento se ele já estiver inicializado e desejar executar uma atualização incremental manual e não programada para transferir dados imediatamente. 
---
= Inicializando ou atualizando relacionamentos de proteção a partir da página de detalhes de integridade/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar uma transferência de linha de base pela primeira vez em um novo relacionamento de proteção ou atualizar um relacionamento se ele já estiver inicializado e desejar executar uma atualização incremental manual e não programada para transferir dados imediatamente.



== Antes de começar

* Você deve ter a função Administrador do OnCommand ou Administrador do armazenamento.
* Tem de ter configurado o OnCommand Workflow Automation.




== Passos

. Na guia *proteção* da página de detalhes *Saúde/volume*, localize na topologia a relação de proteção que você deseja inicializar ou atualizar e clique com o botão direito do Mouse nela.
. Selecione *Inicializar/Atualizar* no menu.
+
Alternativamente, no menu *ações*, selecione *relacionamento* > *Inicializar/Atualizar* para inicializar ou atualizar a relação para a qual você está visualizando os detalhes no momento.

+
A caixa de diálogo Inicializar/Atualizar é exibida.

. Na guia *Opções de transferência*, selecione uma prioridade de transferência e a taxa de transferência máxima.
. Clique em *cópias snapshot de origem*; em seguida, na coluna *cópia Snapshot*, clique em *predefinição*.
+
A caixa de diálogo Selecionar cópia Snapshot de origem é exibida.

. Se você quiser especificar uma cópia Snapshot existente em vez de transferir a cópia Snapshot padrão, clique em *cópia Snapshot existente* e selecione uma cópia Snapshot na lista.
. Clique em *Enviar*.
+
Você será retornado à caixa de diálogo Inicializar/Atualizar.

. Se você selecionou mais de uma fonte para inicializar ou atualizar, clique em *Default* para a próxima fonte de leitura/gravação para a qual deseja especificar uma cópia Snapshot existente.
+
Não é possível selecionar uma cópia Snapshot diferente para volumes de proteção de dados.

. Clique em *Enviar* para iniciar o trabalho de inicialização ou atualização.
+
O trabalho de inicialização ou atualização é iniciado, você retorna à página de detalhes de integridade/volume e um link trabalhos é exibido na parte superior da página.

. Clique em *Exibir trabalhos* na página de detalhes *Saúde/volume* para rastrear o status de cada tarefa de inicialização ou atualização.
+
É apresentada uma lista filtrada de trabalhos.

. Clique em cada trabalho para ver os seus detalhes.
. Clique na seta para trás do seu navegador para retornar à página de detalhes *Saúde/volume*.
+
A operação de inicialização ou atualização é concluída quando todas as tarefas de trabalho forem concluídas com êxito.


