---
permalink: performance-checker/reference-performance-event-severity-types.html 
sidebar: sidebar 
keywords:  
summary: Cada evento de performance está associado a um tipo de gravidade para ajudar você a priorizar os eventos que exigem ação corretiva imediata. 
---
= Tipos de gravidade de eventos de performance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada evento de performance está associado a um tipo de gravidade para ajudar você a priorizar os eventos que exigem ação corretiva imediata.

* *Crítica*
+
Ocorreu um evento de desempenho que pode levar a interrupção do serviço se uma ação corretiva não for tomada imediatamente.

+
Eventos críticos são enviados apenas a partir de limites definidos pelo usuário.

* *Aviso*
+
Um contador de desempenho para um objeto de cluster está fora do intervalo normal e deve ser monitorado para garantir que ele não atinja a gravidade crítica. Os eventos desta gravidade não causam interrupções no serviço e podem não ser necessárias ações corretivas imediatas.

+
Os eventos de aviso são enviados a partir de limites definidos pelo usuário, definidos pelo sistema ou dinâmicos.

* *Informação*
+
O evento ocorre quando um novo objeto é descoberto ou quando uma ação do usuário é executada. Por exemplo, quando qualquer objeto de armazenamento é excluído ou quando há alterações de configuração, o evento com informações de tipo de gravidade é gerado.

+
Os eventos de informação são enviados diretamente do ONTAP quando deteta uma alteração de configuração.


