---
permalink: health-checker/task-changing-the-umadmin-password-on-rhel.html 
sidebar: sidebar 
keywords:  
summary: Por motivos de segurança, você deve alterar a senha padrão do usuário umadmin do Unified Manager imediatamente após concluir o processo de instalação. Se necessário, você pode alterar a senha novamente a qualquer momento mais tarde. 
---
= Alterar a senha umadmin em sistemas Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por motivos de segurança, você deve alterar a senha padrão do usuário umadmin do Unified Manager imediatamente após concluir o processo de instalação. Se necessário, você pode alterar a senha novamente a qualquer momento mais tarde.



== Antes de começar

* É necessário instalar o Unified Manager em um sistema Red Hat Enterprise Linux ou CentOS Linux.
* Você deve ter as credenciais de usuário raiz para o sistema Linux no qual o Unified Manager está instalado.




== Passos

. Faça login como usuário raiz no sistema Linux no qual o Unified Manager está sendo executado.
. Altere a senha umadmin: `passwd umadmin`
+
O sistema solicita que você insira uma nova senha para o usuário umadmin.





== Depois de terminar

Se o Unified Manager estiver instalado em um ambiente do Veritas Cluster Server (VCS), você deverá alterar a senha umadmin no segundo nó da configuração do VCS. A senha umadmin para ambos os nós deve ser a mesma.
