---
permalink: health-checker/task-changing-the-maintenance-user-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: Você pode alterar a senha do usuário de manutenção do Unified Manager quando necessário. 
---
= Alterar a palavra-passe do utilizador de manutenção no Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar a senha do usuário de manutenção do Unified Manager quando necessário.



== Passos

. Na página de login da IU da Web do Unified Manager, clique em *Esqueceu a senha*.
+
É apresentada uma página que solicita o nome do utilizador cuja palavra-passe pretende repor.

. Digite o nome de usuário e clique em *Enviar*.
+
Um e-mail com um link para redefinir a senha é enviado para o endereço de e-mail definido para esse nome de usuário.

. Clique no link *RESET password* no e-mail e defina a nova senha.
. Retorne à IU da Web e faça login no Unified Manager usando a nova senha.




== Depois de terminar

Se o Unified Manager estiver instalado em um ambiente Microsoft Cluster Server (MSCS), você deverá alterar a senha do usuário de manutenção no segundo nó da configuração do MSCS. A senha do usuário de manutenção para ambos os nós deve ser a mesma.
