---
permalink: health-checker/task-removing-a-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: 'Você pode remover uma relação de proteção para excluir permanentemente uma relação existente entre a origem e o destino selecionados: Por exemplo, quando você deseja criar uma relação usando um destino diferente. Esta operação remove todos os metadados e não pode ser desfeita.' 
---
= Remover uma relação de proteção da página de detalhes de integridade/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover uma relação de proteção para excluir permanentemente uma relação existente entre a origem e o destino selecionados: Por exemplo, quando você deseja criar uma relação usando um destino diferente. Esta operação remove todos os metadados e não pode ser desfeita.



== Antes de começar

* Você deve ter a função Administrador do OnCommand ou Administrador do armazenamento.
* Você deve ter configurado o Workflow Automation.




== Passos

. Na guia *proteção* da página de detalhes *Saúde/volume*, selecione na topologia a relação do SnapMirror que deseja remover.
. Clique com o botão direito do rato no nome do destino e selecione *Remover* no menu.
+
A caixa de diálogo Remover relacionamento é exibida.

. Clique em *continuar* para remover o relacionamento.
+
A relação é removida da página de detalhes de integridade/volume.


