---
permalink: install/concept-browser-and-platform-requirements.html 
sidebar: sidebar 
keywords:  
summary: Para acessar a IU do Unified Manager, você deve usar um navegador compatível. 
---
= Navegadores suportados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para acessar a IU do Unified Manager, você deve usar um navegador compatível.

O Unified Manager foi testado com os seguintes navegadores: Outros navegadores podem funcionar, mas não foram qualificados. Consulte a Matriz de interoperabilidade para obter a lista completa de versões de navegador suportadas.

http://mysupport.netapp.com/matrix["mysupport.NetApp.com/matrix"]

* Mozilla Firefox ESR 60
* Google Chrome versão 68 e 69
* Microsoft Internet Explorer 11


Para todos os navegadores, desativar os bloqueadores popup ajuda a garantir que os recursos do software sejam exibidos corretamente.

Para o Internet Explorer, você deve garantir que a Exibição de Compatibilidade esteja desativada e o modo de documento esteja definido como padrão. Consulte a documentação do Microsoft IE para obter informações sobre essas configurações.

[NOTE]
====
O Firefox e o Chrome são os navegadores preferidos, já que houve alguns casos em que páginas complexas da interface do usuário carregam mais lentamente ao usar o Internet Explorer.

====
Se você estiver planejando configurar o Unified Manager para autenticação SAML para que um provedor de identidade (IDP) autentique usuários, verifique também a lista de navegadores suportados pelo IDP.
