---
permalink: install/task-changing-the-jboss-password.html 
sidebar: sidebar 
keywords:  
summary: Você pode criar uma nova senha JBoss personalizada para substituir a senha padrão definida durante a instalação. Essa tarefa é opcional, mas alguns sites podem exigir esse recurso de segurança para substituir a configuração padrão de instalação do Unified Manager. Esta operação também altera a senha que o JBoss usa para acessar o MySQL. 
---
= Alterar a senha do JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar uma nova senha JBoss personalizada para substituir a senha padrão definida durante a instalação. Essa tarefa é opcional, mas alguns sites podem exigir esse recurso de segurança para substituir a configuração padrão de instalação do Unified Manager. Esta operação também altera a senha que o JBoss usa para acessar o MySQL.



== Antes de começar

* É necessário ter acesso de usuário raiz ao sistema Red Hat Enterprise Linux ou CentOS no qual o Unified Manager está instalado.
* Você deve ser capaz de acessar o script fornecido pelo NetApp `password.sh` no diretório `/opt/netapp/essentials/bin`.




== Passos

. Inicie sessão como utilizador raiz no sistema.
. Pare os serviços do Unified Manager inserindo os seguintes comandos na ordem mostrada: `service ocieau stop``service ocie stop`
+
Não pare o software MySQL associado.

. Digite o seguinte comando para iniciar o processo de alteração de senha: `/opt/netapp/essentials/bin/password.sh resetJBossPassword`
. Quando solicitado, insira a senha antiga do JBoss.
+
A senha padrão é `D11h1aMu@79%`.

. Quando solicitado, digite a nova senha do JBoss e insira-a uma segunda vez para confirmação.
. Quando o script for concluído, inicie os serviços do Unified Manager inserindo os seguintes comandos na ordem mostrada: `service ocie start``service ocieau start`
. Depois que todos os serviços forem iniciados, você poderá fazer login na IU do Unified Manager.

