---
permalink: install/task-installing-unified-manager-on-windows.html 
sidebar: sidebar 
keywords:  
summary: Você pode instalar o Unified Manager no Windows para monitorar e solucionar problemas de capacidade, disponibilidade, desempenho e proteção de storage de dados. 
---
= Instalar o Unified Manager em um sistema Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode instalar o Unified Manager no Windows para monitorar e solucionar problemas de capacidade, disponibilidade, desempenho e proteção de storage de dados.



== Antes de começar

* O sistema no qual você planeja instalar o Unified Manager deve atender aos requisitos de sistema e software.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Requisitos do sistema de hardware]

+
xref:reference-windows-software-and-installation-requirements.adoc[Requisitos de software e instalação do Windows]

+
[NOTE]
====
A partir do Unified Manager 9,5, o OpenJDK é fornecido no pacote de instalação do Unified Manager e instalado automaticamente. O Oracle Java não é suportado a partir do Unified Manager 9,5.

====
* Você deve ter o Privileges administrador do Windows.
* Você deve ter um navegador da Web compatível.
* A senha do usuário de manutenção do Unified Manager deve ter entre 8 e 20 carateres, deve conter letras maiúsculas ou minúsculas, números e carateres especiais.
* Os seguintes carateres especiais não são permitidos na cadeia de carateres de senha para o usuário de manutenção ou para o usuário raiz MySQL: "
+
Os seguintes carateres especiais são permitidos: * - ? . Selecione a opção "OK"





== Passos

. Inicie sessão no Windows utilizando a conta de administrador local predefinida.
. Faça login no site de suporte da NetApp e localize a página de download para instalar o Unified Manager na plataforma Windows.
+
http://mysupport.netapp.com/NOW/cgi-bin/software["Downloads de NetApp: Software"]

. Baixe o arquivo de instalação do Gerenciador Unificado do Windows do site de suporte da NetApp para um diretório de destino no sistema Windows.
. Navegue até o diretório onde o arquivo de instalação está localizado.
. Clique com o botão direito do rato e execute o (`.exe`ficheiro executável do instalador do Unified Manager ) como administrador.
+
O Unified Manager deteta pacotes de terceiros ausentes ou pré-instalados e os lista. Se os pacotes de terceiros necessários não estiverem instalados no sistema, o Unified Manager os instalará como parte da instalação.

. Clique em *seguinte*.
. Introduza o nome de utilizador e a palavra-passe para criar o utilizador de manutenção.
. No assistente *Database Connection*, insira a senha raiz do MySQL.
. Clique em *Change* para especificar um novo local para o diretório de instalação do Unified Manager e o diretório de dados MySQL.
+
Se você não alterar o diretório de instalação, o Unified Manager será instalado no diretório de instalação padrão.

. Clique em *seguinte*.
. No assistente *Ready to Install Shield*, clique em *Install*.
. Após a conclusão da instalação, clique em *Finish*.




== Resultados

A instalação cria vários diretórios:

* Diretório de instalação
+
Este é o diretório raiz do Unified Manager, que você especificou durante a instalação. Exemplo: `C:\Program Files\NetApp\`

* Diretório de dados MySQL
+
Este é o diretório onde os bancos de dados MySQL são armazenados, que você especificou durante a instalação. Exemplo: `C:\ProgramData\MySQL\MySQLServerData\`

* Diretório Java
+
Este é o diretório onde o OpenJDK será instalado. Exemplo: `C:\Program Files\NetApp\JDK\`

* Diretório de dados do aplicativo do Unified Manager (appDataDir)
+
Este é o diretório onde todos os dados gerados pela aplicação são armazenados. Isso inclui logs, pacotes de suporte, backup e todos os outros dados adicionais. Exemplo: `C:\ProgramData\NetApp\OnCommandAppData\`





== Depois de terminar

Você pode acessar a IU da Web para executar a configuração inicial do Unified Manager, conforme descrito em link:../config/concept-configuring-unified-manager.html["Configurando o Unified Manager"].
