---
permalink: install/task-upgrading-mysql-on-windows-ocum.html 
sidebar: sidebar 
keywords: OnCommand Unified Manager 
summary: Você pode atualizar para uma versão mais recente do MySQL no servidor Windows no qual o Unified Manager está instalado para obter correções para vulnerabilidades de segurança. 
---
= Atualizando MySQL no Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar para uma versão mais recente do MySQL no servidor Windows no qual o Unified Manager está instalado para obter correções para vulnerabilidades de segurança.



== Antes de começar

* Você deve ter o Privileges de administrador do Windows para o sistema no qual o Unified Manager está instalado.
* Você deve ter a senha para o usuário root MySQL.




== Passos

. Faça login como usuário admin na máquina host do Unified Manager.
. Baixe a versão apropriada do MySQL para o sistema de destino.
. Use o console dos Serviços do Windows para interromper os seguintes serviços do Unified Manager:
+
** Unidade de aquisição NetApp OCIE (Ocie-au)
** Servidor de aplicativos NetApp OnCommand (Oncommandsvc)
** MYSQL


. Clique no `.msi` pacote para chamar a atualização do MySQL e siga as instruções na tela para concluir a atualização.
. Inicie os serviços do Unified Manager usando o console dos Serviços do Windows:
+
** MYSQL
** Servidor de aplicativos NetApp OnCommand (Oncommandsvc)
** Unidade de aquisição NetApp OCIE (Ocie-au)



